
--CREACION T_USUARIO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id (N'T_USUARIO'))
DROP TABLE T_USUARIO;

GO

CREATE TABLE T_USUARIO(

	CORREO 						VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,
	NOMBRE_USUARIO 				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,
	CONTRASENA		 			VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,
	FOTO				 		VARCHAR(100) NULL,
	FECHA_NACIMIENTO 			VARCHAR(100) NULL, 
	NOMBRE			 			VARCHAR(100) COLLATE Modern_Spanish_CI_AI NULL,
	APELLIDOS 					VARCHAR(100) COLLATE Modern_Spanish_CI_AI NULL,
	DESCRIPCION 				VARCHAR(500) COLLATE Modern_Spanish_CI_AI NULL,
	PROCEDENCIA	 				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NULL,

CONSTRAINT PK_USUARIO PRIMARY KEY CLUSTERED
(
	NOMBRE_USUARIO 				ASC
)
);

GO


--CREACION T_DEGUSTACION

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id (N'T_DEGUSTACION'))
DROP TABLE T_DEGUSTACION;

GO

CREATE TABLE T_DEGUSTACION(

	ID_DEGUSTACION				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,
	NOMBRE 						VARCHAR(100) COLLATE Modern_Spanish_CI_AI NULL,
	CALIFICADOR 				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NULL,
	TIPO		 				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NULL,
	FOTO				 		VARCHAR(100) nulL,
	REGION 						VARCHAR(100) COLLATE Modern_Spanish_CI_AI NULL,
	USUARIO_ANADE				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NULL,
	LOCAL_ANADE					VARCHAR(100) COLLATE Modern_Spanish_CI_AI NULL,

CONSTRAINT PK_DEGUSTACION PRIMARY KEY CLUSTERED
(
	ID_DEGUSTACION 				ASC
)
);


--CREACION T_LOCAL

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id (N'T_LOCAL'))
DROP TABLE T_LOCAL;

GO

CREATE TABLE T_LOCAL(

	NOMBRE 						VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,
	COORDENADAS 				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NULL,
	DIRECCION		 			VARCHAR(100) COLLATE Modern_Spanish_CI_AI NULL,
	AGREGA						VARCHAR(100) COLLATE Modern_Spanish_CI_AI NULL,
	FECHA_AGREGA				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NULL,

CONSTRAINT PK_LOCAL PRIMARY KEY CLUSTERED
(
	NOMBRE 				ASC
)
);


--CREACION T_GALARDON

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id (N'T_GALARDON'))
DROP TABLE T_GALARDON;

GO

CREATE TABLE T_GALARDON(

	NOMBRE 						VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,
	NIVEL 						NUMERIC(4),
	IMAGEN		 				VARBINARY(MAX),
	INTRODUCE					VARCHAR(100) COLLATE Modern_Spanish_CI_AI NULL,

CONSTRAINT PK_GALARDON PRIMARY KEY CLUSTERED
(
	NOMBRE 				ASC
)
);

--CREACION T_DEGUSTA

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id (N'T_DEGUSTA'))
DROP TABLE T_DEGUSTA;

GO

CREATE TABLE T_DEGUSTA(

	ID_DEGUSTACION 				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,
	NOMBRE_USUARIO 				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,
	ORDEN						NUMERIC(4),	

CONSTRAINT PK_DEGUSTA PRIMARY KEY CLUSTERED
(
	ID_DEGUSTACION 				ASC,
	NOMBRE_USUARIO				ASC
),
FOREIGN KEY (ID_DEGUSTACION) REFERENCES T_DEGUSTACION(ID_DEGUSTACION) ON UPDATE CASCADE,
FOREIGN KEY (NOMBRE_USUARIO) REFERENCES T_USUARIO(NOMBRE_USUARIO) ON UPDATE CASCADE
);

--CREACION T_TIENE_FAVORITOS

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id (N'T_TIENE_FAVORITOS'))
DROP TABLE T_TIENE_FAVORITOS;

GO

CREATE TABLE T_TIENE_FAVORITOS(

	ID_DEGUSTACION 				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,
	NOMBRE_USUARIO 				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,

CONSTRAINT PK_TIENE_FAVORITOS PRIMARY KEY CLUSTERED
(
	ID_DEGUSTACION 				ASC,
	NOMBRE_USUARIO				ASC
),
FOREIGN KEY (ID_DEGUSTACION) REFERENCES T_DEGUSTACION(ID_DEGUSTACION) ON UPDATE CASCADE,
FOREIGN KEY (NOMBRE_USUARIO) REFERENCES T_USUARIO(NOMBRE_USUARIO) ON UPDATE CASCADE
);

--CREACION T_CALIFICA

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id (N'T_CALIFICA'))
DROP TABLE T_CALIFICA;

GO

CREATE TABLE T_CALIFICA(

	ID_DEGUSTACION 				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,
	NOMBRE_USUARIO 				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,
	CALIFICACION				NUMERIC(4),	

CONSTRAINT PK_CALIFICA PRIMARY KEY CLUSTERED
(
	ID_DEGUSTACION 				ASC,
	NOMBRE_USUARIO				ASC
),
FOREIGN KEY (ID_DEGUSTACION) REFERENCES T_DEGUSTACION(ID_DEGUSTACION) ON UPDATE CASCADE,
FOREIGN KEY (NOMBRE_USUARIO) REFERENCES T_USUARIO(NOMBRE_USUARIO) ON UPDATE CASCADE
);


--CREACION T_GANA

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id (N'T_GANA'))
DROP TABLE T_GANA;

GO

CREATE TABLE T_GANA(

	NOMBRE_GALARDON 			VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,
	NOMBRE_USUARIO 				VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,

CONSTRAINT PK_GANA PRIMARY KEY CLUSTERED
(
	NOMBRE_GALARDON 			ASC,
	NOMBRE_USUARIO				ASC
),
FOREIGN KEY (NOMBRE_USUARIO) REFERENCES T_USUARIO(NOMBRE_USUARIO)
);

--CREACION T_ADMINISTRADOR

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id (N'T_ADMINISTRADOR'))
DROP TABLE T_ADMINISTRADOR;

GO

CREATE TABLE T_ADMINISTRADOR(

	CORREO 						VARCHAR(100) COLLATE Modern_Spanish_CI_AI NOT NULL,

CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY CLUSTERED
(
	CORREO						ASC
)
);